### ISSUE TITLE
Installation 

### ISSUE THREAD

**Issue by sourdougie** [anbai106/mlni#3]
Hello, 
I had to follow some slightly different steps to get pyHYDRA running here on windows 10. Might have just been because I'm a noob, but I thought I would share here anyway. 

1) conda create --name pyHYDRA python=3.6

2) conda activate pyHYDRA 

3) pip install –r requirements.txt 

4) pip install –r install_requirements.sh

5) pip install pyhydra==1.0.8

6) pip install -e .

Thanks.

**Comment by anbai106** [comment]
I have never tested pyHYDRA on Windows, only work with Ubuntu or Mac. It may be slightly different. Be creative to make things work! I'll leave this issue open in case others run into similar situations.

Thank you
