### ISSUE TITLE
Balanced data

### ISSUE THREAD

**Issue by sourdougie** [anbai106/mlni#4]
Hi Junhao,
One more question. Just wanted to make sure I've understood the code correctly.
By default, HYDRA (for clustering) assumes the data is balanced.
In my data, I have more controls than patients, so I should put in false for this argument?

Thanks,
Jonah

**Comment by anbai106** [comment]
Hi Jonah,

You should leave the argument **class_weight_balanced** to be True by default. SVM from sklearn will deal with imbalanced data with tricks. 

Also, re., the influence of sample size or data imbalance, we have our preliminary semi-simulated results here: [preprint](https://www.biorxiv.org/content/10.1101/2021.04.19.440501v1.abstract). We hope this can offer a guideline for users like you in real applications. This may give you a general hint if your results are reasonable or not.

**Comment by sourdougie** [comment]
Great, thanks for clarifying!
