### ISSUE TITLE
index is out of bounds error

### ISSUE THREAD

**Issue by sourdougie** [anbai106/mlni#5]
Hi Junhao,
I'm getting a small error when running pyHYDRA for clustering at certain cv iterations. It seems to be dependent on the size of my sample, i.e. with a dataset of 804 rows I didn't get any errors when running 100 cv iterations, but with a dataset with 725 rows I got the error below. However, the 725 row dataset worked with 99 cv iterations.

Just thought I should mention, thanks again for your great work on this software!
Best,
Jonah

`pyhydra for semi-supervised clustering...
Data split was performed based on validation strategy: hold_out...

Data split has been done!

Starts semi-supervised clustering...
		[                                                  ] 1.00%
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-9-4063c5835d55> in <module>
      7 cv_repetition=100
      8 covariate_tsv="210516cov.tsv"
----> 9 clustering(feature_tsv, output_dir, k_min, k_max, cv_repetition, covariate_tsv = covariate_tsv)

~\anaconda3\envs\pyHYDRA_NUMBER2\lib\site-packages\pyhydra\hydra_clustering.py in clustering(feature_tsv, output_dir, k_min, k_max, cv_repetition, covariate_tsv, cv_strategy, save_models, cluster_predefined_c, class_weight_balanced, weight_initialization_type, num_iteration, num_consensus, tol, n_threads, verbose)
     80                                                        n_threads=n_threads, save_models=save_models, verbose=verbose)
     81 
---> 82     wf_clustering.run()
     83     print('Finish...')

~\anaconda3\envs\pyHYDRA_NUMBER2\lib\site-packages\pyhydra\clustering.py in run(self)
     54                 if self._verbose:
     55                     print('Applying pyHRDRA for finding %d clusters. Repetition: %d / %d...\n' % (j, i+1, self._cv_repetition))
---> 56                 training_final_prediction = hydra_solver_svm(i, x[self._split_index[i][0]], y[self._split_index[i][0]], j, self._output_dir,
     57                                                          self._num_consensus, self._num_iteration, self._tol, self._balanced, self._predefined_c,
     58                                                          self._weight_initialization_type, self._n_threads, self._save_models, self._verbose)

IndexError: index 748 is out of bounds for axis 0 with size 725`

**Comment by anbai106** [comment]
@sourdougie 
Thank you for the report! The error came from the fact that the data split was done for your first run (904 rows). I assume that you did not change the output_dir or delete the previous data split .pickle file. That's why this happens. I may correct this with a warning message for the next version. 
So for now, can you delete the output and rerun your analysis? 

Also, I am renaming the package since this software does not only contain HYDRA for clustering. You can install the new version if you want, but this does not affect the HYDRA algorithm

Best regards

**Comment by sourdougie** [comment]
@anbai106 
Ah I see, that worked, my bad.
Thanks for explaining!
