### ISSUE TITLE
A question about use of Hydra (or other algorithms) with longitudinal data

### ISSUE THREAD

**Issue by joshleelab** [anbai106/mlni#8]
I have a longitudinal autism dataset and I noted in the instructions of mlni that there is a required session variable. Does this mean that Hydra handles repeated data in some way?
So far I've run it on a single time point.

**Comment by anbai106** [comment]
Hey, HYDRA does not explicitly handle longitudinal data during modeling. What you can do is to train the model using baseline data and apply the data to the longitudinal scans. 

Hopefully, this is helpful!

**Comment by joshleelab** [comment]
Thanks. Briefly, if you don't mind, is it problematic with this method to use features of different modalities together (e.g. categorical with continuous, or behavioral with imaging features) which may have different levels of noise and distributions?

**Comment by anbai106** [comment]
This is a very interesting question. Originally, the method was developed for single-modality subtyping, i.e., imaging features. One can post-hoc correlate this to other feature cross-modalties.

I think the package will work, although I'm unsure how easy/difficult the model will converge. However, I think it is more challenging to interpret the derived subtypes. 

We have developed another mult-view deep learning method (Gene-SGAN), which is a subtyping method based on imaging and genetics:  https://github.com/zhijian-yang/GeneSGAN

**Comment by joshleelab** [comment]
Thanks I'll take a look at it. And again, thanks for making this package! I'll be sure to cite your work if it makes it way to a paper.
